### ISSUE TITLE
Helm resources/history not showing

### ISSUE THREAD

**Issue by georgi-at-skribble** [guiqui/k8Studio#83] opened 2024-05-02 08:54 UTC
---------
App Version 1.0.6-beta
Arch: arm64
Platform: darwin
osRelease: 23.4.0
Locale: en-GB
---------

Hey Folks, I just started playing around today and noticed something. When I want to see the resources that belong to a release or the history revisions- it just not working. It keeps loading and nothing showing up. I tried multiple times and rebooting the app. May be once or twice I was able to see something, but only on a very small releases with couple of objects, but that was it. 

![helm_resources](https://github.com/guiqui/k8Studio/assets/122033253/db8a01f3-b634-4f29-9472-c873a50ff461)

**Comment by mo-othman** [comment] 2024-05-02 09:56
Hi @georgi-at-skribble 
Thanks for reporting this! We are investigating the issue.

I have a question
Are you using a proxy to connect to the cluster?

**Comment by georgi-at-skribble** [comment] 2024-05-02 12:27
nope. As I said again: Sometimes it works for example for appsmith deployment and it shows the objects and history, but it is a very small deployment( only a couple of objects), But when I try to lookup my staging deployment with 100+ objects, it just ...keeps loading.

**Comment by mo-othman** [comment] 2024-05-02 14:28
Hi @georgi-at-skribble Can we know your helm cli version?

**Comment by georgi-at-skribble** [comment] 2024-05-02 14:46
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}

**Comment by mo-othman** [comment] 2024-05-03 12:43
Hi

We have have fixed the issue and released 1.0.7-beta

let me know if it's working with the new release

**Comment by georgi-at-skribble** [comment] 2024-05-03 13:34
I updated and tried again, with no success :(. Also update helm and cleaned up my kube/config a little bit.

But now when I think about it and tried again- it works for all "public" helm charts installed on the cluster, like appsmith, grafana and etc. It does not work for our own(internal) helm charts...It seems that the problem is somewhere in our charts I guess...

**Comment by mo-othman** [comment] 2024-05-03 13:38
Do you still have the same error or a different error?
Also if you run helm get manifest RELEASE through the terminal is it working?

**Comment by georgi-at-skribble** [comment] 2024-05-03 13:43
It works in the console yes. You have my email in the support mail. You can hit me with a meet link and I can show you quickly.

**Comment by mo-othman** [comment] 2024-05-03 14:16
Hi @georgi-at-skribble 

What time are you available? Are you available now?

**Comment by georgi-at-skribble** [comment] 2024-05-08 07:37
I just tried 1.0.8 and it works now!

It was really nice talking to you. Thanks for your support!

**Comment by mo-othman** [comment] 2024-06-06 13:54
Thanks @georgi-at-skribble 
I'm gonna close this ticket since the issue is resolved

just to let you know, we have released 1.0.9
it includes improvements in the layout (esp when you are using microservices) and secrets decode
<img width="1046" alt="Screenshot 2024-06-06 205035" src="https://github.com/guiqui/k8Studio/assets/42744048/deff25f3-c907-493b-ba07-fc7dfb144122">

**Closed by mo-othman** 2024-06-06 13:54 UTC
